import Head from 'next/head'
import {Container, MainStyled} from '../components/sharedstyles'
import Card from '../components/cards/card'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Nft Preview</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600&display=swap" rel="stylesheet"/>
        <link rel="icon" href="./images/favicon-32x32.png" />
      </Head>
      <MainStyled>
        <Card/>
      </MainStyled>
    </Container>
  )
}
